CONFIG = {}

-- This is off for now because I want to make sure that it works
-- If events aren't registered on the network it will probably ban them
-- Hopefully we don't have any poorly coded scripts that attempt to call
-- Events without registering them first :fingers_crossed: 
CONFIG.BAN_FOR_ILLEGALLY_CALLING_EVENTS = true

CONFIG.DEBUG_EVENTS = false
CONFIG.ANTICHEAT_WEBHOOK = ""

CONFIG.BLACKLISTED_WORDS = {
    ["nigger"] = true,
    ["nlgger"] = true,
    ["n1gg3r"] = true,
    ["nigga"] = true,
    ["nigger"] = true,
    ["nigg"] = true,
    ["nigga"] = true,
    ["nickgur"] = true,
    ["nlgga"] = true,
    ["niglet"] = true,
    ["niqqa"] = true,
    ["niqqer"] = true,
    ["niga"] = true,
    ["nibber"] = true,
    ["nibba"] = true,
    ["ngigers"] = true,
    ["niggers"] = true,
    ["wigger"] = true,
    ["wiggers"] = true,
    ["niggerz"] = true,
}

CONFIG.BLOCKED_MODELS = {
    [`rhino`] = true,
    [`jet`] = true,
    [`stt_prop_stunt_track_uturn`] = true,
    [`stt_prop_stunt_track_turnice`] = true,
    [`stt_prop_stunt_track_hill`] = true,
    [`prop_gold_cont_01`] = true,
    [`p_cablecar_s`] = true,
    [`stt_prop_stunt_tube_l`] = true,
    [`stt_prop_stunt_track_dwuturn`] = true,
    [`prop_fnclink_05crnr1`] = true,
    [`pounder2`] = true,
    [`xs_prop_hamburgher_wl`] = true,
    [`xs_prop_plastic_bottle_wl`] = true,
    [`prop_windmill_01`] = true,
    [`p_spinning_anus_s`] = true,
    [`stt_prop_ramp_adj_flip_m`] = true,
    [`stt_prop_ramp_adj_flip_mb`] = true,
    [`stt_prop_ramp_adj_flip_s`] = true,
    [`stt_prop_ramp_adj_flip_sb`] = true,
    [`stt_prop_ramp_adj_hloop`] = true,
    [`stt_prop_ramp_adj_loop`] = true,
    [`ardent`] = true,
    [`stt_prop_ramp_jump_l`] = true,
    [`stt_prop_ramp_jump_m`] = true,
    [`stt_prop_ramp_jump_s`] = true,
    [`stt_prop_ramp_jump_xl`] = true,
    [`stt_prop_ramp_jump_xs`] = true,
    [`stt_prop_ramp_jump_xxl`] = true,
    [`stt_prop_ramp_multi_loop_rb`] = true,
    [`stt_prop_ramp_spiral_l`] = true,
    [`stt_prop_ramp_spiral_l_l`] = true,
    [`stt_prop_ramp_spiral_l_m`] = true,
    [`stt_prop_ramp_spiral_l_s`] = true,
    [`stt_prop_ramp_spiral_l_xxl`] = true,
    [`stt_prop_ramp_spiral_m`] = true,
    [`stt_prop_ramp_spiral_s`] = true,
    [`stt_prop_ramp_spiral_xxl`] = true,
    [`stt_prop_stunt_track_dwslope30`] = true,
    [-145066854] = true,
    [`stt_prop_stunt_track_start`] = true,
    [`stt_prop_stunt_track_slope45`] = true,
    [`stt_prop_stunt_track_slope30`] = true,
    [`stt_prop_stunt_track_slope15`] = true,
    [`stt_prop_stunt_track_short`] = true,
    [`stt_prop_stunt_track_sh45_a`] = true,
    [`stt_prop_stunt_track_sh45`] = true,
    [`stt_prop_stunt_track_sh30`] = true,
    [`stt_prop_stunt_track_sh15`] = true,
    [`stt_prop_stunt_track_otake`] = true,
    [`stt_prop_stunt_track_link`] = true,
    [`stt_prop_stunt_track_jump`] = true,
    [`stt_prop_stunt_track_hill2`] = true,
    [`stt_prop_stunt_track_hill`] = true,
    [`stt_prop_stunt_track_funnel`] = true,
    [`stt_prop_stunt_track_funlng`] = true,
    [`stt_prop_stunt_track_fork`] = true,
    [`stt_prop_stunt_track_exshort`] = true,
    [`stt_prop_stunt_track_dwuturn`] = true,
    [`stt_prop_stunt_track_dwturn`] = true,
    [`stt_prop_stunt_track_dwslope45`] = true,
    [`stt_prop_stunt_track_dwslope30`] = true,
    [`stt_prop_stunt_track_dwslope15`] = true,
    [`stt_prop_stunt_track_dwshort`] = true,
    [`stt_prop_stunt_track_dwsh15`] = true,
    [`stt_prop_stunt_track_dwlink_02`] = true,
    [`stt_prop_stunt_track_dwlink`] = true,
    [`stt_prop_stunt_track_cutout`] = true,
    [`stt_prop_stunt_track_bumps`] = true,
    [`stt_prop_stunt_target_small`] = true,
    [`stt_prop_stunt_target`] = true,
    [`stt_prop_stunt_soccer_sball`] = true,
    [`stt_prop_stunt_soccer_lball`] = true,
    [`stt_prop_stunt_soccer_goal`] = true,
    [`stt_prop_stunt_soccer_ball`] = true,
    [`stt_prop_stunt_ramp`] = true,
    [`stt_prop_stunt_landing_zone_01`] = true,
    [`stt_prop_stunt_jump_sb`] = true,
    [`stt_prop_stunt_jump_s`] = true,
    [`stt_prop_stunt_jump_mb`] = true,
    [`stt_prop_stunt_jump_m`] = true,
    [`stt_prop_stunt_jump_loop`] = true,
    [`stt_prop_stunt_jump_lb`] = true,
    [`stt_prop_stunt_jump_l`] = true,
    [`stt_prop_stunt_jump45`] = true,
    [`stt_prop_stunt_jump30`] = true,
    [`stt_prop_stunt_jump15`] = true,
    [`stt_prop_stunt_domino`] = true,
    [`prop_weed_pallet`] = true,
    [`hei_prop_carrier_radar_1_l1`] = true,
    [`v_res_mexball`] = true,
    [`prop_rock_1_a`] = true,
    [`prop_rock_1_b`] = true,
    [`prop_rock_1_c`] = true,
    [`prop_rock_1_d`] = true,
    [`prop_player_gasmask`] = true,
    [`prop_rock_1_e`] = true,
    [`prop_rock_1_f`] = true,
    [`prop_rock_1_g`] = true,
    [`prop_rock_1_h`] = true,
    [`prop_test_boulder_01`] = true,
    [`prop_test_boulder_02`] = true,
    [`prop_test_boulder_03`] = true,
    [`prop_test_boulder_04`] = true,
    [`apa_mp_apa_crashed_usaf_01a`] = true,
    [`ex_prop_exec_crashdp`] = true,
    [`apa_mp_apa_yacht_o1_rail_a`] = true,
    [`apa_mp_apa_yacht_o1_rail_b`] = true,
    [`apa_mp_h_yacht_armchair_01`] = true,
    [`apa_mp_h_yacht_armchair_03`] = true,
    [`apa_mp_h_yacht_armchair_04`] = true,
    [`apa_mp_h_yacht_barstool_01`] = true,
    [`apa_mp_h_yacht_bed_01`] = true,
    [`apa_mp_h_yacht_bed_02`] = true,
    [`apa_mp_h_yacht_coffee_table_01`] = true,
    [`apa_mp_h_yacht_coffee_table_02`] = true,
    [`apa_mp_h_yacht_floor_lamp_01`] = true,
    [`apa_mp_h_yacht_side_table_01`] = true,
    [`apa_mp_h_yacht_side_table_02`] = true,
    [`apa_mp_h_yacht_sofa_01`] = true,
    [`apa_mp_h_yacht_sofa_02`] = true,
    [`apa_mp_h_yacht_stool_01`] = true,
    [`apa_mp_h_yacht_strip_chair_01`] = true,
    [`apa_mp_h_yacht_table_lamp_01`] = true,
    [`apa_mp_h_yacht_table_lamp_02`] = true,
    [`apa_mp_h_yacht_table_lamp_03`] = true,
    [`apa_mp_apa_yacht_o2_rail_a`] = true,
    [`apa_mp_apa_yacht_o2_rail_b`] = true,
    [`apa_mp_apa_yacht_o3_rail_a`] = true,
    [`apa_mp_apa_yacht_o3_rail_b`] = true,
    [`apa_mp_apa_yacht_option1`] = true,
    [`proc_searock_01`] = true,
    [`apa_mp_h_yacht_`] = true,
    [`apa_mp_apa_yacht_option1_cola`] = true,
    [`apa_mp_apa_yacht_option2`] = true,
    [`apa_mp_apa_yacht_option2_cola`] = true,
    [`apa_mp_apa_yacht_option2_colb`] = true,
    [`apa_mp_apa_yacht_option3`] = true,
    [`apa_mp_apa_yacht_option3_cola`] = true,
    [`apa_mp_apa_yacht_option3_colb`] = true,
    [`apa_mp_apa_yacht_option3_colc`] = true,
    [`apa_mp_apa_yacht_option3_cold`] = true,
    [`apa_mp_apa_yacht_option3_cole`] = true,
    [`apa_mp_apa_yacht_jacuzzi_cam`] = true,
    [`apa_mp_apa_yacht_jacuzzi_ripple003`] = true,
    [`apa_mp_apa_yacht_jacuzzi_ripple1`] = true,
    [`apa_mp_apa_yacht_jacuzzi_ripple2`] = true,
    [`apa_mp_apa_yacht_radar_01a`] = true,
    [`apa_mp_apa_yacht_win`] = true,
    [`prop_crashed_heli`] = true,
    [`apa_mp_apa_yacht_door`] = true,
    [`prop_shamal_crash`] = true,
    [`xm_prop_x17_shamal_crash`] = true,
    [`apa_mp_apa_yacht_door2`] = true,
    [`apa_mp_apa_yacht`] = true,
    [`apa_prop_yacht_float_1a`] = true,
    [`apa_prop_yacht_float_1b`] = true,
    [`apa_prop_yacht_glass_01`] = true,
    [`apa_prop_yacht_glass_02`] = true,
    [`apa_prop_yacht_glass_03`] = true,
    [`apa_prop_yacht_glass_04`] = true,
    [`apa_prop_yacht_glass_05`] = true,
    [`apa_prop_yacht_glass_06`] = true,
    [`apa_prop_yacht_glass_07`] = true,
    [`apa_prop_yacht_glass_08`] = true,
    [`apa_prop_yacht_glass_09`] = true,
    [`apa_prop_yacht_glass_10`] = true,
    [`prop_target_blue_arrow`] = true,
    [`prop_target_orange_arrow`] = true,
    [`prop_target_purp_arrow`] = true,
    [`prop_target_red_arrow`] = true,
    [`sr_prop_spec_tube_xxs_01a`] = true,
    [`prop_flamingo`] = true,
    [`prop_swiss_ball_01`] = true,
    [`prop_air_bigradar_l1`] = true,
    [`prop_air_bigradar_l2`] = true,
    [`prop_air_bigradar_slod`] = true,
    [`p_fib_rubble_s`] = true,
    [`prop_money_bag_01`] = true,
    [`p_cs_mp_jet_01_s`] = true,
    [`prop_poly_bag_money`] = true,
    [`prop_air_radar_01`] = true,
    [`hei_prop_carrier_radar_1`] = true,
    [`prop_air_bigradar`] = true,
    [`prop_carrier_radar_1_l1`] = true,
    [`prop_asteroid_01`] = true,
    [`p_oil_pjack_01_amo`] = true,
    [`p_oil_pjack_01_s`] = true,
    [`p_oil_pjack_02_amo`] = true,
    [`p_oil_pjack_03_amo`] = true,
    [`p_oil_pjack_02_s`] = true,
    [`p_oil_pjack_03_s`] = true,
    [`prop_aircon_l_03`] = true,
    [`prop_med_jet_01`] = true,
    [`p_med_jet_01_s`] = true,
    [`hei_prop_carrier_jet`] = true,
    [`bkr_prop_biker_bblock_huge_01`] = true,
    [`bkr_prop_biker_bblock_huge_02`] = true,
    [`bkr_prop_biker_bblock_huge_04`] = true,
    [`bkr_prop_biker_bblock_huge_05`] = true,
    [`hei_prop_heist_emp`] = true,
    [`prop_weed_01`] = true,
    [`prop_air_bigradar`] = true,
    [`prop_juicestand`] = true,
    [`prop_lev_des_barge_02`] = true,
    [`hei_prop_carrier_defense_01`] = true,
    [`prop_aircon_m_04`] = true,
    [`prop_mp_ramp_03`] = true,
    [`stt_prop_stunt_track_dwuturn`] = true,
    [`ch3_12_animplane1_lod`] = true,
    [`ch3_12_animplane2_lod`] = true,
    [`hei_prop_hei_pic_pb_plane`] = true,
    [`light_plane_rig`] = true,
    [`prop_cs_plane_int_01`] = true,
    [`prop_dummy_plane`] = true,
    [`prop_mk_plane`] = true,
    [`v_44_planeticket`] = true,
    [`prop_planer_01`] = true,
    [`ch3_03_cliffrocks03b_lod`] = true,
    [`ch3_04_rock_lod_02`] = true,
    [`csx_coastsmalrock_01_`] = true,
    [`csx_coastsmalrock_02_`] = true,
    [`csx_coastsmalrock_03_`] = true,
    [`csx_coastsmalrock_04_`] = true,
    [`mp_player_introck`] = true,
    [`Heist_Yacht`] = true,
    [`csx_coastsmalrock_05_`] = true,
    [`mp_player_int_rock`] = true,
    [`mp_player_introck`] = true,
    [`prop_a4_pile_01`] = true,
    [`cs2_10_sea_rocks_lod`] = true,
    [`cs2_11_sea_marina_xr_rocks_03_lod`] = true,
    [`prop_gold_cont_01`] = true,
    [`prop_hydro_platform`] = true,
    [`ch3_04_viewplatform_slod`] = true,
    [`ch2_03c_rnchstones_lod`] = true,
    [`proc_mntn_stone01`] = true,
    [`proc_mntn_stone02`] = true,
    [`cs2_10_sea_shipwreck_lod`] = true,
    [`des_shipsink_02`] = true,
    [`prop_dock_shippad`] = true,
    [`des_shipsink_03`] = true,
    [`des_shipsink_04`] = true,
    [`proc_mntn_stone03`] = true,
    [`FreeModeMale01`] = true,
    [`rsn_os_specialfloatymetal_n`] = true,
    [`rsn_os_specialfloatymetal`] = true,
    [`cs1_09_sea_ufo`] = true,
    [`rsn_os_specialfloaty2_light2`] = true,
    [`rsn_os_specialfloaty2_light`] = true,
    [`rsn_os_specialfloaty2`] = true,
    [`rsn_os_specialfloatymetal_n`] = true,
    [`rsn_os_specialfloatymetal`] = true,
    [`P_Spinning_Anus_S_Main`] = true,
    [`P_Spinning_Anus_S_Root`] = true,
    [`cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a`] = true,
    [`sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a`] = true,
    [`rnbj_wallsigns_0001`] = true,
    [`proc_sml_stones01`] = true,
    [`proc_sml_stones02`] = true,
    [`proc_sml_stones03`] = true,
    [`proc_stones_01`] = true,
    [`proc_stones_02`] = true,
    [`proc_stones_03`] = true,
    [`proc_stones_04`] = true,
    [`proc_stones_05`] = true,
    [`proc_stones_06`] = true,
    [`prop_coral_stone_03`] = true,
    [`prop_coral_stone_04`] = true,
    [`prop_gravestones_01a`] = true,
    [`prop_gravestones_02a`] = true,
    [`prop_gravestones_03a`] = true,
    [`prop_gravestones_04a`] = true,
    [`prop_gravestones_05a`] = true,
    [`prop_gravestones_06a`] = true,
    [`prop_gravestones_07a`] = true,
    [`prop_gravestones_08a`] = true,
    [`prop_gravestones_09a`] = true,
    [`prop_gravestones_10a`] = true,
    [`prop_prlg_gravestone_05a_l1`] = true,
    [`prop_prlg_gravestone_06a`] = true,
    [`test_prop_gravestones_04a`] = true,
    [`test_prop_gravestones_05a`] = true,
    [`test_prop_gravestones_07a`] = true,
    [`test_prop_gravestones_08a`] = true,
    [`test_prop_gravestones_09a`] = true,
    [`prop_prlg_gravestone_01a`] = true,
    [`prop_prlg_gravestone_02a`] = true,
    [`prop_prlg_gravestone_03a`] = true,
    [`prop_prlg_gravestone_04a`] = true,
    [`prop_stoneshroom1`] = true,
    [`prop_stoneshroom2`] = true,
    [`v_res_fa_stones01`] = true,
    [`test_prop_gravestones_01a`] = true,
    [`test_prop_gravestones_02a`] = true,
    [`prop_prlg_gravestone_05a`] = true,
    [`FreemodeFemale01`] = true,
    [`p_cablecar_s`] = true,
    [`stt_prop_stunt_tube_l`] = true,
    [`stt_prop_stunt_track_dwuturn`] = true,
    [`p_spinning_anus_s`] = true,
    [`prop_windmill_01`] = true,
    [`hei_prop_heist_tug`] = true,
    [`prop_air_bigradar`] = true,
    [`p_oil_slick_01`] = true,
    [`prop_dummy_01`] = true,
    [`hei_prop_heist_emp`] = true,
    [`p_tram_cash_s`] = true,
    [`hw1_blimp_ce2`] = true,
    [`prop_fire_exting_1a`] = true,
    [`prop_fire_exting_1b`] = true,
    [`prop_fire_exting_2a`] = true,
    [`prop_fire_exting_3a`] = true,
    [`hw1_blimp_ce2_lod`] = true,
    [`hw1_blimp_ce_lod`] = true,
    [`hw1_blimp_cpr003`] = true,
    [`hw1_blimp_cpr_null`] = true,
    [`hw1_blimp_cpr_null2`] = true,
    [`prop_lev_des_barage_02`] = true,
    [`hei_prop_carrier_defense_01`] = true,
    [`prop_juicestand`] = true,
    [`S_M_M_MovAlien_01`] = true,
    [`s_m_m_movalien_01`] = true,
    [`s_m_m_movallien_01`] = true,
    [`u_m_y_babyd`] = true,
    [`CS_Orleans`] = true,
    [`A_M_Y_ACult_01`] = true,
    [`S_M_M_MovSpace_01`] = true,
    [`U_M_Y_Zombie_01`] = true,
    [`s_m_y_blackops_01`] = true,
    [`a_f_y_topless_01`] = true,
    [`a_c_boar`] = true,
    [`a_c_cat_01`] = true,
    [`a_c_chickenhawk`] = true,
    [`a_c_chimp`] = true,
    [`s_f_y_hooker_03`] = true,
    [`a_c_chop`] = true,
    [`a_c_cormorant`] = true,
    [`a_c_cow`] = true,
    [`a_c_coyote`] = true,
    [`v_ilev_found_cranebucket`] = true,
    [`p_cs_sub_hook_01_s`] = true,
    [`a_c_crow`] = true,
    [`a_c_dolphin`] = true,
    [`a_c_fish`] = true,
    [`hei_prop_heist_hook_01`] = true,
    [`prop_rope_hook_01`] = true,
    [`prop_sub_crane_hook`] = true,
    [`s_f_y_hooker_01`] = true,
    [`prop_vehicle_hook`] = true,
    [`prop_v_hook_s`] = true,
    [`prop_dock_crane_02_hook`] = true,
    [`prop_winch_hook_long`] = true,
    [`a_c_hen`] = true,
    [`a_c_humpback`] = true,
    [`a_c_husky`] = true,
    [`a_c_killerwhale`] = true,
    [`a_c_mtlion`] = true,
    [`a_c_pigeon`] = true,
    [`a_c_poodle`] = true,
    [`prop_coathook_01`] = true,
    [`prop_cs_sub_hook_01`] = true,
    [`a_c_pug`] = true,
    [`a_c_rabbit_01`] = true,
    [`a_c_rat`] = true,
    [`a_c_retriever`] = true,
    [`a_c_rhesus`] = true,
    [`a_c_rottweiler`] = true,
    [`a_c_sharkhammer`] = true,
    [`a_c_sharktiger`] = true,
    [`a_c_shepherd`] = true,
    [`a_c_stingray`] = true,
    [`a_c_westy`] = true,
    [`CS_Orleans`] = true,
    [`prop_windmill_01`] = true,
    [`prop_Ld_ferris_wheel`] = true,
    [`p_tram_crash_s`] = true,
    [`p_oil_slick_01`] = true,
    [`p_ld_soc_ball_01`] = true,
    [`p_parachute1_s`] = true,
    [`p_cablecar_s`] = true,
    [`prop_beach_fire`] = true,
    [`prop_lev_des_barge_02`] = true,
    [`prop_lev_des_barge_01`] = true,
    [`prop_sculpt_fix`] = true,
    [`prop_winch_hook_short`] = true,
    [`prop_ld_hook`] = true,
    [`prop_cable_hook_01`] = true,
    [`csx_coastboulder_00`] = true,
    [`des_tankercrash_01`] = true,
    [`des_tankerexplosion_01`] = true,
    [`des_tankerexplosion_02`] = true,
    [`des_trailerparka_02`] = true,
    [`des_trailerparkb_02`] = true,
    [`des_trailerparkc_02`] = true,
    [`des_trailerparkd_02`] = true,
    [`des_traincrash_root2`] = true,
    [`des_traincrash_root3`] = true,
    [`des_traincrash_root4`] = true,
    [`des_traincrash_root5`] = true,
    [`des_finale_vault_end`] = true,
    [`des_finale_vault_root001`] = true,
    [`des_finale_vault_root002`] = true,
    [`des_finale_vault_root003`] = true,
    [`des_finale_vault_root004`] = true,
    [`des_finale_vault_start`] = true,
    [`des_vaultdoor001_root001`] = true,
    [`des_vaultdoor001_root002`] = true,
    [`des_vaultdoor001_root003`] = true,
    [`des_vaultdoor001_root004`] = true,
    [`des_vaultdoor001_root005`] = true,
    [`des_vaultdoor001_root006`] = true,
    [`des_vaultdoor001_skin001`] = true,
    [`des_vaultdoor001_start`] = true,
    [`des_traincrash_root6`] = true,
    [`prop_ld_vault_door`] = true,
    [`prop_vault_door_scene`] = true,
    [`prop_vault_door_scene`] = true,
    [`prop_vault_shutter`] = true,
    [`p_fin_vaultdoor_s`] = true,
    [`prop_gold_vault_fence_l`] = true,
    [`prop_gold_vault_fence_r`] = true,
    [`prop_gold_vault_gate_01`] = true,
    [`des_traincrash_root7`] = true,
    [`ch2_03c_props_rrlwindmill_lod`] = true,
    [`prop_yacht_lounger`] = true,
    [`prop_yacht_seat_01`] = true,
    [`prop_yacht_seat_02`] = true,
    [`prop_yacht_seat_03`] = true,
    [`marina_xr_rocks_02`] = true,
    [`marina_xr_rocks_03`] = true,
    [`prop_test_rocks01`] = true,
    [`prop_test_rocks02`] = true,
    [`prop_test_rocks03`] = true,
    [`prop_test_rocks04`] = true,
    [`marina_xr_rocks_04`] = true,
    [`marina_xr_rocks_05`] = true,
    [`marina_xr_rocks_06`] = true,
    [`prop_yacht_table_01`] = true,
    [`csx_searocks_02`] = true,
    [`csx_searocks_03`] = true,
    [`csx_searocks_04`] = true,
    [`csx_searocks_05`] = true,
    [`csx_searocks_06`] = true,
    [`p_yacht_chair_01_s`] = true,
    [`p_yacht_sofa_01_s`] = true,
    [`prop_yacht_table_02`] = true,
    [`csx_coastboulder_00`] = true,
    [`csx_coastboulder_01`] = true,
    [`csx_coastboulder_02`] = true,
    [`csx_coastboulder_03`] = true,
    [`csx_coastboulder_04`] = true,
    [`csx_coastboulder_05`] = true,
    [`csx_coastboulder_06`] = true,
    [`csx_coastboulder_07`] = true,
    [`csx_coastrok1`] = true,
    [`csx_coastrok2`] = true,
    [`csx_coastrok3`] = true,
    [`csx_coastrok4`] = true,
    [`csx_coastsmalrock_01`] = true,
    [`csx_coastsmalrock_02`] = true,
    [`csx_coastsmalrock_03`] = true,
    [`csx_coastsmalrock_04`] = true,
    [`csx_coastsmalrock_05`] = true,
    [`prop_yacht_table_03`] = true,
    [`p_gasmask_s`] = true,
    [`prop_flamingo`] = true,
    [`comet4`] = true,
    [`RHINO`] = true,
    [`Zentorno`] = true,
    [`xa21`] = true,
    [`voltic2`] = true,
    [`voltic`] = true,
    [`visione`] = true,
    [`vigilante`] = true,
    [`vagner`] = true,
    [`vacca`] = true,
    [`tyrus`] = true,
    [`tyrant`] = true,
    [`turismor`] = true,
    [`tezeract`] = true,
    [`tempesta`] = true,
    [`taipan`] = true,
    [`t20`] = true,
    [`sultan4s`] = true,
    [`sheava`] = true,
    [`scramjet`] = true,
    [`sc1`] = true,
    [`reaper`] = true,
    [`prototipo`] = true,
    [`reaper`] = true,
    [`pfister881`] = true,
    [`penetrator`] = true,
    [`osiris`] = true,
    [`nero2`] = true,
    [`nero`] = true,
    [`le7b`] = true,
    [`italigtb2`] = true,
    [`italigtb`] = true,
    [`infernus`] = true,
    [`gp1`] = true,
    [`fmj`] = true,
    [`entity2`] = true,
    [`entityxf`] = true,
    [`deveste`] = true,
    [`cyclone`] = true,
    [`adder`] = true,
    [`autarch`] = true,
    [`bansee2`] = true,
    [`bullet`] = true,
    [`phantom2`] = true,
    [`apc`] = true,
    [`barrage`] = true,
    [`chernobog`] = true,
    [`halftrack`] = true,
    [`khanjali`] = true,
    [`scarab`] = true,
    [`scarab2`] = true,
    [`scarab3`] = true,
    [`thruster`] = true,
    [`trailersmall2`] = true,
    [`bullet`] = true,
    [`ambulance`] = true,
    [`fbi`] = true,
    [`fbi2`] = true,
    [`firetruk`] = true,
    [`police`] = true,
    [`police2`] = true,
    [`police3`] = true,
    [`police4`] = true,
    [`policeb`] = true,
    [`policeold1`] = true,
    [`policeold2`] = true,
    [`policet`] = true,
    [`polmav`] = true,
    [`pranger`] = true,
    [`predator`] = true,
    [`riot`] = true,
    [`riot2`] = true,
    [`sheriff`] = true,
    [`sheriff2`] = true,
    [`brickade`] = true,
    [`blimp`] = true,
    [`blimp2`] = true,
    [`blimp3`] = true,
    [`cargoplane`] = true,
    [`bombushka`] = true,
    [`volatol`] = true,
    [`strikeforce`] = true,
    [`lazer`] = true,
    [`hydra`] = true,
    [`valkyrie2`] = true,
    [`valkyrie`] = true,
    [`skylift`] = true,
    [`savage`] = true,
    [`hunter`] = true,
    [`buzzard`] = true,
    [`annihilator`] = true,
    [`predator`] = true,
    [`boxville5`] = true,
    [`trailerlarge`] = true,
    [`dump`] = true,
    [`cutter`] = true,
    [`technical3`] = true,
    [`technical2`] = true,
    [`technical`] = true,
    [`nightshark`] = true,
    [`rcbandito`] = true,
    [`monster5`] = true,
    [`monster4`] = true,
    [`monster3`] = true,
    [`monster`] = true,
    [`menacer`] = true,
    [`insurgent3`] = true,
    [`insurgent2`] = true,
    [`insurgent`] = true,
    [`dune5`] = true,
    [`dune4`] = true,
    [`dune3`] = true,
    [`dune2`] = true,
    [`caracara`] = true,
    [`brutus3`] = true,
    [`brutus2`] = true,
    [`brutus`] = true,
    [`bruister3`] = true,
    [`bruiser2`] = true,
    [`bruiser`] = true,
    [`blazar5`] = true,
    [`shotaro`] = true,
    [`oppressor2`] = true,
    [`oppressor`] = true,
    [`hakuchou2`] = true,
    [`hakuchou`] = true,
    [`deathbike3`] = true,
    [`deathbike2`] = true,
    [`deathbike`] = true,
    [`zr3803`] = true,
    [`zr3802`] = true,
    [`zr380`] = true,
    [`schafter5`] = true,
    [`schafter6`] = true,
    [`kuruma2`] = true,
    [`tampa3`] = true,
    [`slamvan6`] = true,
    [`slamvan5`] = true,
    [`slamvan4`] = true,
    [`ruiner3`] = true,
    [`ruiner2`] = true,
    [`xls2`] = true,
    [`pyro`] = true,
    [`baller6`] = true,
    [`baller5`] = true,
    [`limo2`] = true,
    [`cog552`] = true,
    [`cognoscenti2`] = true,
    [`issi6`] = true,
    [`issi5`] = true,
    [`issi4`] = true,
    [`bullet`] = true,
    [`bullet`] = true,
    [`bullet`] = true,
    [`akula`] = true,
    [`jet`] = true,
    [`mogul`] = true,
    [`cargobob2`] = true,
    [`cargobob3`] = true,
    [`cargobob4`] = true,
    [`tula`] = true,
    [`cerberus`] = true,
    [`cerberus2`] = true,
    [`cerberus3`] = true,
    [`marshall`] = true,
    [`starling`] = true,
    [`rogue`] = true,
    [`warrener2`] = true,
    [`previon`] = true,
    [`calico`] = true,
    [`euros`] = true,
    [`jester4`] = true,
    [`sultan3`] = true,
    [`vectre`] = true,
    [`zr350`] = true,
    [`molotok`] = true,
    [`bruiser3`] = true,
    [`speedo4`] = true,
    [`blazer5`] = true,
    [`dominator4`] = true,
    [`dominator5`] = true,
    [`dominator6`] = true,
    [`impaler2`] = true,
    [`impaler3`] = true,
    [`imperator`] = true,
    [`imperator2`] = true,
    [`imperator3`] = true,
    [`nokota`] = true,
    [`deluxo`] = true,
    [`towtruck`] = true,
    [`stromberg`] = true,
    [`impaler4`] = true,
    [`towtruck2`] = true,
    [`savestra`] = true,
    [`tug`] = true,
    [`minitank`] = true,
    [`buzzard`] = true,
    [`mule4`] = true,
    [`jb7002`] = true,
    [`revolter`] = true,
    [-1701919363] = true,
    [1765283457] = true,
    [`prop_doghouse_01`] = true,
    [`prop_fnclink_05crnr1`] = true,
    [-699955605] = true,
    [2081936690] = true,
    [-343452421] = true,
    [1124049486] = true,
    [-1170462683] = true,
    [-1404196790] = true,
    [1125864094] = true,
    [993442923] = true,
    [1322181531] = true,
    [2042825373] = true,
    [`stt_prop_stunt_bblock_huge_01`] = true,
    [`stt_prop_stunt_bblock_huge_02`] = true,
    [`stt_prop_stunt_bblock_huge_03`] = true,
    [`stt_prop_stunt_bblock_huge_04`] = true,
    [`stt_prop_stunt_bblock_huge_05`] = true,
    [`stt_prop_stunt_bblock_hump_01`] = true,
    [`stt_prop_stunt_bblock_hump_02`] = true,
    [`stt_prop_stunt_bblock_lrg1`] = true,
    [`stt_prop_stunt_bblock_lrg2`] = true,
    [`stt_prop_stunt_bblock_lrg3`] = true,
    [`stt_prop_stunt_bblock_mdm1`] = true,
    [`stt_prop_stunt_bblock_mdm2`] = true,
    [`stt_prop_stunt_bblock_mdm3`] = true,
    [`stt_prop_stunt_bblock_qp`] = true,
    [`stt_prop_stunt_bblock_qp2`] = true,
    [`stt_prop_stunt_bblock_qp3`] = true,
    [`stt_prop_stunt_bblock_sml1`] = true,
    [`stt_prop_stunt_bblock_sml2`] = true,
    [`stt_prop_stunt_bblock_sml3`] = true,
    [`stt_prop_stunt_bblock_xl1`] = true,
    [`stt_prop_stunt_bblock_xl2`] = true,
    [`stt_prop_stunt_bblock_xl3`] = true,
    [`stt_prop_stunt_bowling_ball`] = true,
    [`stt_prop_stunt_bowling_pin`] = true,
    [`stt_prop_stunt_bowlpin_stand`] = true,
    [`stt_prop_stunt_jump15`] = true,
    [`stt_prop_stunt_jump30`] = true,
    [`stt_prop_stunt_jump45`] = true,
    [`stt_prop_stunt_jump_l`] = true,
    [`stt_prop_stunt_jump_lb`] = true,
    [`stt_prop_stunt_jump_loop`] = true,
    [`stt_prop_stunt_jump_m`] = true,
    [`stt_prop_stunt_jump_mb`] = true,
    [`stt_prop_stunt_jump_s`] = true,
    [`stt_prop_stunt_jump_sb`] = true,
    [`stt_prop_stunt_landing_zone_01`] = true,
    [`stt_prop_stunt_ramp`] = true,
    [`stt_prop_stunt_soccer_ball`] = true,
    [`stt_prop_stunt_soccer_goal`] = true,
    [`stt_prop_stunt_soccer_lball`] = true,
    [`stt_prop_stunt_soccer_sball`] = true,
    [`stt_prop_stunt_target`] = true,
    [`stt_prop_stunt_target_small`] = true,
    [`stt_prop_stunt_track_bumps`] = true,
    [`stt_prop_stunt_track_cutout`] = true,
    [`stt_prop_stunt_track_dwlink`] = true,
    [`stt_prop_stunt_track_dwlink_02`] = true,
    [`stt_prop_stunt_track_dwsh15`] = true,
    [`stt_prop_stunt_track_dwshort`] = true,
    [`stt_prop_stunt_track_dwslope15`] = true,
    [`stt_prop_stunt_track_dwslope30`] = true,
    [`stt_prop_stunt_track_dwslope45`] = true,
    [`stt_prop_stunt_track_dwturn`] = true,
    [`stt_prop_stunt_track_dwuturn`] = true,
    [`stt_prop_stunt_track_exshort`] = true,
    [`stt_prop_stunt_track_fork`] = true,
    [`stt_prop_stunt_track_funlng`] = true,
    [`stt_prop_stunt_track_funnel`] = true,
    [`stt_prop_stunt_track_hill`] = true,
    [`stt_prop_stunt_track_hill2`] = true,
    [`stt_prop_stunt_track_jump`] = true,
    [`stt_prop_stunt_track_link`] = true,
    [`stt_prop_stunt_track_otake`] = true,
    [`stt_prop_stunt_track_sh15`] = true,
    [`stt_prop_stunt_track_sh30`] = true,
    [`stt_prop_stunt_track_sh45`] = true,
    [`stt_prop_stunt_track_sh45_a`] = true,
    [`stt_prop_stunt_track_short`] = true,
    [`stt_prop_stunt_track_slope15`] = true,
    [`stt_prop_stunt_track_slope30`] = true,
    [`stt_prop_stunt_track_slope45`] = true,
    [`stt_prop_stunt_track_st_01`] = true,
    [`stt_prop_stunt_track_st_02`] = true,
    [`stt_prop_stunt_track_start`] = true,
    [`stt_prop_stunt_track_start_02`] = true,
    [`stt_prop_stunt_track_straight`] = true,
    [`stt_prop_stunt_track_straightice`] = true,
    [`stt_prop_stunt_track_turn`] = true,
    [`stt_prop_stunt_track_turnice`] = true,
    [`stt_prop_stunt_track_uturn`] = true,
    [`stt_prop_stunt_tube_crn`] = true,
    [`stt_prop_stunt_tube_crn2`] = true,
    [`stt_prop_stunt_tube_crn_15d`] = true,
    [`stt_prop_stunt_tube_crn_30d`] = true,
    [`stt_prop_stunt_tube_crn_5d`] = true,
    [`stt_prop_stunt_tube_cross`] = true,
    [`stt_prop_stunt_tube_end`] = true,
    [`stt_prop_stunt_tube_ent`] = true,
    [`stt_prop_stunt_tube_fn_01`] = true,
    [`stt_prop_stunt_tube_fn_02`] = true,
    [`stt_prop_stunt_tube_fn_03`] = true,
    [`stt_prop_stunt_tube_fn_04`] = true,
    [`stt_prop_stunt_tube_fn_05`] = true,
    [`stt_prop_stunt_tube_fork`] = true,
    [`stt_prop_stunt_tube_gap_01`] = true,
    [`stt_prop_stunt_tube_gap_02`] = true,
    [`stt_prop_stunt_tube_gap_03`] = true,
    [`stt_prop_stunt_tube_hg`] = true,
    [`stt_prop_stunt_tube_jmp`] = true,
    [`stt_prop_stunt_tube_jmp2`] = true,
    [`stt_prop_stunt_tube_l`] = true,
    [`stt_prop_stunt_tube_m`] = true,
    [`stt_prop_stunt_tube_qg`] = true,
    [`stt_prop_stunt_tube_s`] = true,
    [`stt_prop_stunt_tube_speed`] = true,
    [`stt_prop_stunt_tube_speeda`] = true,
    [`stt_prop_stunt_tube_speedb`] = true,
    [`stt_prop_stunt_tube_xs`] = true,
    [`stt_prop_stunt_tube_xxs`] = true,
    [`stt_prop_stunt_wideramp`] = true,
    [`kosatka`] = true,
	[`alkonost`] = true,
	[`PARAGON2`] = true,
    [`hellion6str`] = true,
	[`srt8b`] = true,
	[`buffalo4`] = true,
   	[`Veto`] = true,
   	[`veto2`] = true,
    [`zhaba`] = true,
    [`tractorcv8`] = true,
    [`deity`] = true,
    [`patriot3`] = true,
    [`dinghy5`] = true,
    [`patrolboat`] = true,
    [`previon`] = true,
    [`calico`] = true,
    [`euros`] = true,
    [`jester4`] = true,
    [`sultan3`] = true,
    [`vectre`] = true,
    [`zr350`] = true,
    [`warrener2`] = true,
    [`previon`] = true,
    [`s80`] = true,
    [`jb700`] = true,
    [`zr350`] = true,
}

CONFIG.BLOCKED_COMMANDS = {
    -- ["killmenu"] = true,
	-- ["menu"] = true,
	-- ["chocolate"] = true,
	-- ["lol"] = true,
	-- ["pk"] = true,
	-- ["haha"] = true,
	-- ["panickey"] = true,
	-- ["FunCtionOk"] = true
}

CONFIG.RegisterEventsLate = {
    "dp:ServerKeybindExist",
    "fuel:pay",
    "txaLogger:DeathNotice",
    "wk:onPlateScanned",
    "sonorancad:livemap:UpdatePlayerData",
    "sonorancad:livemap:playerSpawned",
    "dp:ServerKeybindUpdate",
    "sonorancad:livemap:AddPlayerData",
    "sonorancad:livemap:RemovePlayer",
    "kq_wheeldamage:setState",
    "kq_wheeldamage:setBroken",
    "wk:onPlateLocked",
    "__cfx_rpcRep:vMenu",
    "Scene:New",
    "Scene:AttemptDelete",
    "Scene:Request",
    "pma-voice:setTalkingOnRadio",
    "pma-voice:setPlayerRadio",
    "pma-voice:setPlayerCall",
    "pma-voice:addChannelCheck",
    "EasyAdmin:amiadmin",
    "EasyAdmin:requestBanlist",
    "EasyAdmin:requestCachedPlayers",
    "pen:removesubmixsrv",
    "pen:addsubmixsrv",
    "getShouldSendPostal",
    "cadClientPostal",
    "sonoran:tablet:forceCheckApiId",
    "sonoran:tablet:setApiId",
    "SmartSigns:getConfig",
    "Phone:playerLoaded",
	"mm:event3",
	"mm:event2",
	"pen_members_only:PlayerReady",
	"Server:checkUsingDLc",
	"Server:checkusingDlc",
	"SonoranCAD::locations:SendLocation",
	"lvc:TogTkdState_s",
	"txsv:checkAdminStatus",
	"SonoranCAD::core:sendClientConfig",
	"SonoranCAD::forcereg:CheckPlayer",
	"__ox_cb_ethicalpixel-admin:CheckPerms",
	"__cfx_rpcRep:scnp25",
    "phone:messages:messageSent"
}

CONFIG.BLOCKED_EVENTS = {
    "8321hiue89js",
    "adminmenu:allowall",
    "AdminMenu:giveBank",
    "AdminMenu:giveCash",
    "AdminMenu:giveDirtyMoney",
    "Tem2LPs5Para5dCyjuHm87y2catFkMpV",
    "dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
    "antilynx8:anticheat",
    "antilynxr4:detect",
    "antilynxr6:detection",
    "ynx8:anticheat",
    "antilynx8r4a:anticheat",
    "lynx8:anticheat",
    "AntiLynxR4:kick",
    "AntiLynxR4:log",
    "bank:deposit",
    "bank:withdraw",
    "Banca:deposit",
    "Banca:withdraw",
    "BsCuff:Cuff696999",
    "CheckHandcuff",
    "cuffServer",
    "cuffGranted",
    -- "DiscordBot:playerDied",
    "DFWM:adminmenuenable",
    "DFWM:askAwake",
    "DFWM:checkup",
    "DFWM:cleanareaentity",
    "DFWM:cleanareapeds",
    "DFWM:cleanareaveh",
    "DFWM:enable",
    "DFWM:invalid",
    "DFWM:log",
    "DFWM:openmenu",
    "DFWM:spectate",
    "DFWM:ViolationDetected",
    "dmv:success",
    "eden_garage:payhealth",
    "ems:revive",
    "esx_ambulancejob:revive",
    "esx_ambulancejob:setDeathStatus",
    "esx_billing:sendBill",
    "esx_banksecurity:pay",
    "esx_blanchisseur:startWhitening",
    "esx_carthief:alertcops",
    "esx_carthief:pay",
    "esx_dmvschool:addLicense",
    "esx_dmvschool:pay",
    "esx_drugs:startHarvestWeed",
    "esx_drugs:startTransformWeed",
    "esx_drugs:startSellWeed",
    "esx_drugs:startHarvestCoke",
    "esx_drugs:startTransformCoke",
    "esx_drugs:startSellCoke",
    "esx_drugs:startHarvestMeth",
    "esx_drugs:startTransformMeth",
    "esx_drugs:startSellMeth",
    "esx_drugs:startHarvestOpium",
    "esx_drugs:startTransformOpium",
    "esx_drugs:startSellOpium",
    "esx_drugs:stopHarvestCoke",
    "esx_drugs:stopTransformCoke",
    "esx_drugs:stopSellCoke",
    "esx_drugs:stopHarvestMeth",
    "esx_drugs:stopTransformMeth",
    "esx_drugs:stopSellMeth",
    "esx_drugs:stopHarvestWeed",
    "esx_drugs:stopTransformWeed",
    "esx_drugs:stopSellWeed",
    "esx_drugs:stopHarvestOpium",
    "esx_drugs:stopTransformOpium",
    "esx_drugs:stopSellOpium",
    "esx:enterpolicecar",
    "esx_fueldelivery:pay",
    "esx:giveInventoryItem",
    "esx_garbagejob:pay",
    "esx_godirtyjob:pay",
    "esx_gopostaljob:pay",
    "esx_handcuffs:cuffing",
    "esx_jail:sendToJail",
    "esx_jail:unjailQuest",
    "esx_jailer:sendToJail",
    "esx_jailer:unjailTime",
    "esx_jobs:caution",
    "esx_mecanojob:onNPCJobCompleted",
    "esx_mechanicjob:startHarvest",
    "esx_mechanicjob:startCraft",
    "esx_pizza:pay",
    "esx_policejob:handcuff",
    "esx-qalle-jail:jailPlayer",
    "esx-qalle-jail:jailPlayerNew",
    "esx-qalle-hunting:reward",
    "esx-qalle-hunting:sell",
    "esx_ranger:pay",
    "esx:removeInventoryItem",
    "esx_truckerjob:pay",
    "esx_skin:responseSaveSkin",
    "esx_slotmachine:sv:2",
    "esx_society:getOnlinePlayers",
    "esx_society:setJob",
    "esx_vehicleshop:setVehicleOwned",
    "hentailover:xdlol",
    "JailUpdate",
    "js:jailuser",
    "js:removejailtime",
    "LegacyFuel:PayFuel",
    "ljail:jailplayer",
    "lscustoms:payGarage",
    "mellotrainer:adminTempBan",
    "mellotrainer:adminKick",
    "mellotrainer:s_adminKill",
    "NB:destituerplayer",
    "NB:recruterplayer",
    "OG_cuffs:cuffCheckNearest",
    "paramedic:revive",
    "police:cuffGranted",
    "unCuffServer",
    "uncuffGranted",
    "vrp_slotmachine:server:2",
    "whoapd:revive",
    "gcPhone:_internalAddMessageDFWM",
    "gcPhone:tchat_channelDFWM",
    "esx_vehicleshop:setVehicleOwnedDFWM",
    "esx_mafiajob:confiscateDFWMPlayerItem",
    "_chat:messageEntDFWMered",
    "lscustoms:pDFWMayGarage",
    "vrp_slotmachDFWMine:server:2",
    "Banca:dDFWMeposit",
    "bank:depDFWMosit",
    "esx_jobs:caDFWMution",
    "give_back",
    "esx_fueldDFWMelivery:pay",
    "esx_carthDFWMief:pay",
    "esx_godiDFWMrtyjob:pay",
    "esx_pizza:pDFWMay",
    "esx_ranger:pDFWMay",
    "esx_garbageDFWMjob:pay",
    "esx_truckDFWMerjob:pay",
    "AdminMeDFWMnu:giveBank",
    "AdminMDFWMenu:giveCash",
    "esx_goDFWMpostaljob:pay",
    "esx_baDFWMnksecurity:pay",
    "esx_sloDFWMtmachine:sv:2",
    "esx:giDFWMveInventoryItem",
    "NB:recDFWMruterplayer",
    "esx_biDFWMlling:sendBill",
    "esx_jDFWMailer:sendToJail",
    "esx_jaDFWMil:sendToJail",
    "js:jaDFWMiluser",
    "esx-qalle-jail:jailPDFWMlayer",
    "esx_dmvschool:pDFWMay",
    "LegacyFuel:PayFuDFWMel",
    "OG_cuffs:cuffCheckNeDFWMarest",
    "CheckHandcDFWMuff",
    "cuffSeDFWMrver",
    "cuffGDFWMranted",
    "police:cuffGDFWMranted",
    "esx_handcuffs:cufDFWMfing",
    "esx_policejob:haDFWMndcuff",
    "bank:withdDFWMraw",
    "dmv:succeDFWMss",
    "esx_skin:responseSaDFWMveSkin",
    "esx_dmvschool:addLiceDFWMnse",
    "esx_mechanicjob:starDFWMtCraft",
    "esx_drugs:startHarvestWDFWMeed",
    "esx_drugs:startTransfoDFWMrmWeed",
    "esx_drugs:startSellWeDFWMed",
    "esx_drugs:startHarvestDFWMCoke",
    "esx_drugs:startTransDFWMformCoke",
    "esx_drugs:startSellCDFWMoke",
    "esx_drugs:startHarDFWMvestMeth",
    "esx_drugs:startTDFWMransformMeth",
    "esx_drugs:startSellMDFWMeth",
    "esx_drugs:startHDFWMarvestOpium",
    "esx_drugs:startSellDFWMOpium",
    "esx_drugs:starDFWMtTransformOpium",
    "esx_blanchisDFWMseur:startWhitening",
    "esx_drugs:stopHarvDFWMestCoke",
    "esx_drugs:stopTranDFWMsformCoke",
    "esx_drugs:stopSellDFWMCoke",
    "esx_drugs:stopHarvesDFWMtMeth",
    "esx_drugs:stopTranDFWMsformMeth",
    "esx_drugs:stopSellMDFWMeth",
    "esx_drugs:stopHarDFWMvestWeed",
    "esx_drugs:stopTDFWMransformWeed",
    "esx_drugs:stopSellWDFWMeed",
    "esx_drugs:stopHarvestDFWMOpium",
    "esx_drugs:stopTransDFWMformOpium",
    "esx_drugs:stopSellOpiuDFWMm",
    "esx_society:openBosDFWMsMenu",
    "esx_jobs:caDFWMution",
    "esx_tankerjob:DFWMpay",
    "esx_vehicletrunk:givDFWMeDirty",
    "gambling:speDFWMnd",
    "AdminMenu:giveDirtyMDFWMoney",
    "esx_moneywash:depoDFWMsit",
    "esx_moneywash:witDFWMhdraw",
    "mission:completDFWMed",
    "truckerJob:succeDFWMss",
    "99kr-burglary:addMDFWMoney",
    "esx_jailer:unjailTiDFWMme",
    "esx_ambulancejob:reDFWMvive",
    "DiscordBot:plaDFWMyerDied",
    "esx:getShDFWMaredObjDFWMect",
    "esx_society:getOnlDFWMinePlayers",
    "js:jaDFWMiluser",
    "h:xd",
    "adminmenu:setsalary",
    "adminmenu:cashoutall",
    "bank:tranDFWMsfer",
    "paycheck:bonDFWMus",
    "paycheck:salDFWMary",
    "HCheat:TempDisableDetDFWMection",
    "esx_drugs:pickedUpCDFWMannabis",
    "esx_drugs:processCDFWMannabis",
    "esx-qalle-hunting:DFWMreward",
    "esx-qalle-hunting:seDFWMll",
    "esx_mecanojob:onNPCJobCDFWMompleted",
    "BsCuff:Cuff696DFWM999",
    "veh_SR:CheckMonDFWMeyForVeh",
    "esx_carthief:alertcoDFWMps",
    "mellotrainer:adminTeDFWMmpBan",
    "mellotrainer:adminKickDFWM",
    "esx_society:putVehicleDFWMInGarage",
    "esx:getSharedObject"
}

local toRemove = {}
for k, v in pairs(CONFIG.BLOCKED_COMMANDS) do
    if k:lower() ~= k then
        CONFIG.BLOCKED_COMMANDS[k:lower()] = true
        table.insert(toRemove, k)
    end
end
for k, v in ipairs(toRemove) do CONFIG.BLOCKED_COMMANDS[k] = nil end
